"""vendor marketplace updates

Revision ID: 01382042c6dd
Revises: ca5df1f3bb53
Create Date: 2026-05-29 11:27:38.121946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01382042c6dd'
down_revision: Union[str, None] = 'ca5df1f3bb53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_orders', sa.Column('vendor_product_id', sa.Integer(), nullable=True))
    op.drop_constraint('vendor_orders_vendor_id_fkey', 'vendor_orders', type_='foreignkey')
    op.create_foreign_key(None, 'vendor_orders', 'vendor_products', ['vendor_product_id'], ['id'], ondelete='SET NULL')
    op.drop_column('vendor_orders', 'vendor_id')
    op.create_unique_constraint(None, 'vendor_products', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor_products', type_='unique')
    op.add_column('vendor_orders', sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vendor_orders', type_='foreignkey')
    op.create_foreign_key('vendor_orders_vendor_id_fkey', 'vendor_orders', 'vendor_products', ['vendor_id'], ['id'], ondelete='SET NULL')
    op.drop_column('vendor_orders', 'vendor_product_id')
    # ### end Alembic commands ###
