"""update the user table

Revision ID: 0be5e296a45a
Revises: 879ccf578fe8
Create Date: 2026-05-17 06:53:38.756880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be5e296a45a'
down_revision: Union[str, None] = '879ccf578fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
