"""add order tracking model

Revision ID: 44c366aa76c0
Revises: 30c6cc93bb58
Create Date: 2026-06-23 08:23:32.521574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c366aa76c0'
down_revision: Union[str, None] = '30c6cc93bb58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('estimate_delivery_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'estimate_delivery_date')
    # ### end Alembic commands ###
