"""add out_for_delivery to order status

Revision ID: aa5b04c7047f
Revises: d503c717f1aa
Create Date: 2026-06-29 12:35:05.328582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5b04c7047f'
down_revision: Union[str, None] = 'd503c717f1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE orderstatus ADD VALUE 'OUT_FOR_DELIVERY';")

    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
