"""change the column name

Revision ID: d04dcc709be0
Revises: 
Create Date: 2026-05-20 09:53:07.204714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04dcc709be0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('farm_name', sa.String(length=150), nullable=True))
    op.drop_column('farmers', 'fram_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('fram_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('farmers', 'farm_name')
    # ### end Alembic commands ###
