"""add order tracking table

Revision ID: d334888009d6
Revises: 44c366aa76c0
Create Date: 2026-06-23 08:25:27.868035

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd334888009d6'
down_revision: Union[str, None] = '44c366aa76c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_type', postgresql.ENUM('PRODUCT', 'VENDOR', name='ordertype', create_type = False), nullable=False),
    sa.Column('product_order_id', sa.Integer(), nullable=True),
    sa.Column('vendor_order_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_order_id'], ['vendor_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_tracking_id'), 'order_tracking', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_tracking_id'), table_name='order_tracking')
    op.drop_table('order_tracking')
    # ### end Alembic commands ###
