"""change in vendor_order model

Revision ID: d503c717f1aa
Revises: d334888009d6
Create Date: 2026-06-23 08:40:27.631939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd503c717f1aa'
down_revision: Union[str, None] = 'd334888009d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_orders', sa.Column('estimated_delivery_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_orders', 'estimated_delivery_date')
    # ### end Alembic commands ###
