"""add a new column in vendorproduct model

Revision ID: e299025c262b
Revises: 01382042c6dd
Create Date: 2026-05-30 10:28:42.383820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e299025c262b'
down_revision: Union[str, None] = '01382042c6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_products', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_products', 'is_available')
    # ### end Alembic commands ###
