"""change the column name

Revision ID: fce2563491f9
Revises: 0be5e296a45a
Create Date: 2026-05-17 07:04:20.928765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce2563491f9'
down_revision: Union[str, None] = '0be5e296a45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.drop_constraint('users_hashed_passsword_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['hashed_password'])
    op.drop_column('users', 'hashed_passsword')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_passsword', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_hashed_passsword_key', 'users', ['hashed_passsword'])
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
